version: '3.4'
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    expose:
      - 5432
  unleash:
    image: unleashorg/unleash-server
    ports:
      - '4242:4242'
    environment:
      DATABASE_URL: 'postgres://postgres:unleash@db/postgres'
      DATABASE_SSL: 'false'
    depends_on:
      - db

networks:
  default:
    external:
      name: unleash-net
